[project]
name = "ipcc"
version = "1.0.0"
requires-python = ">=3.9"
dependencies = [
    "tqdm>=4.66,<5.0"
]

[build-system]
requires = ["setuptools>=65.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["app"]

[tool.pytest.ini_options]
pythonpath = ["."]

[project.scripts]
ipcc = "app.ipcc:main"